Transform: AWS::Serverless-2016-10-31
Resources:
  UpdateGarageState:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: UpdateGarageState
      CodeUri: src/UpdateGarageState
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          GARAGES_TABLE_NAME: !Ref garages
          GARAGES_TABLE_ARN: !GetAtt garages.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref garages
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  UpdateGarageStateLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${UpdateGarageState}
  garages:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: GarageId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: GarageId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  ControlShutter:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ControlShutter
      CodeUri: src/ControlShutter
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          GARAGES_TABLE_NAME: !Ref garages
          GARAGES_TABLE_ARN: !GetAtt garages.Arn
          USERS_TABLE_NAME: !Ref users
          USERS_TABLE_ARN: !GetAtt users.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref garages
        - DynamoDBCrudPolicy:
            TableName: !Ref users
      Events:
        ApiGETgaragesgarageIdshuttercommand:
          Type: Api
          Properties:
            Path: /garages/{garageId}/shutter/{command}
            Method: GET
            RestApiId: !Ref Api
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  ControlShutterLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ControlShutter}
  ControlLight:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ControlLight
      CodeUri: src/ControlLight
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          GARAGES_TABLE_NAME: !Ref garages
          GARAGES_TABLE_ARN: !GetAtt garages.Arn
          USERS_TABLE_NAME: !Ref users
          USERS_TABLE_ARN: !GetAtt users.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref garages
        - DynamoDBCrudPolicy:
            TableName: !Ref users
      Events:
        ApiGETgaragesgarageIdlightcommand:
          Type: Api
          Properties:
            Path: /garages/{garageId}/light/{command}
            Method: GET
            RestApiId: !Ref Api
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  ControlLightLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ControlLight}
  ControlFan:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: ControlFan
      CodeUri: src/ControlFan
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          GARAGES_TABLE_NAME: !Ref garages
          GARAGES_TABLE_ARN: !GetAtt garages.Arn
          USERS_TABLE_NAME: !Ref users
          USERS_TABLE_ARN: !GetAtt users.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref garages
        - DynamoDBCrudPolicy:
            TableName: !Ref users
      Events:
        ApiGETgaragesgarageIdfancommand:
          Type: Api
          Properties:
            Path: /garages/{garageId}/fan/{command}
            Method: GET
            RestApiId: !Ref Api
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  ControlFanLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${ControlFan}
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub
        - ${ResourceName} From Stack ${AWS::StackName}
        - ResourceName: Api
      StageName: Prod
      DefinitionBody:
        openapi: '3.0'
        info: {}
        paths:
          /garages/{garageId}/shutter/{command}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ControlShutter.Arn}/invocations
              responses: {}
          /garages/{garageId}/light/{command}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ControlLight.Arn}/invocations
              responses: {}
          /garages/{garageId}/fan/{command}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ControlFan.Arn}/invocations
              responses: {}
          /garages/{garageId}:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetGarageState.Arn}/invocations
              responses: {}
          /garages/{garageId}/setup:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SetupGarage.Arn}/invocations
              responses: {}
          /garages/{garageId}/request:
            get:
              x-amazon-apigateway-integration:
                httpMethod: POST
                type: aws_proxy
                uri: !Sub arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${RequestGarageState.Arn}/invocations
              responses: {}
      EndpointConfiguration: REGIONAL
      TracingEnabled: true
  users:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: UserId
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: UserId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  GetGarageState:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: GetGarageState
      CodeUri: src/GetGarageState
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref users
          USERS_TABLE_ARN: !GetAtt users.Arn
          GARAGES_TABLE_NAME: !Ref garages
          GARAGES_TABLE_ARN: !GetAtt garages.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref users
        - DynamoDBCrudPolicy:
            TableName: !Ref garages
      Events:
        ApiGETgaragesgarageId:
          Type: Api
          Properties:
            Path: /garages/{garageId}
            Method: GET
            RestApiId: !Ref Api
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  GetGarageStateLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${GetGarageState}
  SetupGarage:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: SetupGarage
      CodeUri: src/SetupGarage
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Events:
        ApiGETgaragesgarageIdsetup:
          Type: Api
          Properties:
            Path: /garages/{garageId}/setup
            Method: GET
            RestApiId: !Ref Api
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref users
          USERS_TABLE_ARN: !GetAtt users.Arn
          GARAGES_TABLE_NAME: !Ref garages
          GARAGES_TABLE_ARN: !GetAtt garages.Arn
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref users
        - DynamoDBCrudPolicy:
            TableName: !Ref garages
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  SetupGarageLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${SetupGarage}
  RequestGarageState:
    Type: AWS::Serverless::Function
    Properties:
      Description: !Sub
        - Stack ${AWS::StackName} Function ${ResourceName}
        - ResourceName: RequestGarageState
      CodeUri: src/RequestGarageState
      Handler: index.handler
      Runtime: nodejs18.x
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Environment:
        Variables:
          USERS_TABLE_NAME: !Ref users
          USERS_TABLE_ARN: !GetAtt users.Arn
      Events:
        ApiGETgaragesgarageIdrequest:
          Type: Api
          Properties:
            Path: /garages/{garageId}/request
            Method: GET
            RestApiId: !Ref Api
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - index.mts
        External:
          - '@aws-sdk/*'
          - aws-sdk
        Minify: false
  RequestGarageStateLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub /aws/lambda/${RequestGarageState}